import { defineStore } from 'pinia'
import { ref } from 'vue'
import type { Product } from '@/types'

export const useProductStore = defineStore('products', () => {
  // 1. Declaramos la variable PRIMERO
  const allProducts = ref<Product[]>([
    {
      id: 1,
      nombre: 'Pantalón Largo Hombre Running Nike Dri-FIT Challenger en Negro',
      referencia: 101,
      descripcion:
        'El pantalón largo Nike Dri-FIT Challenger está diseñado para ofrecerte comodidad y rendimiento.',
      marca: 'Nike',
      precio: 59.99,
      precio_oferta: null,
      visible: true,
      stock: 15,
      genero: 'Hombre',
      tallas: ['S', 'M', 'L', 'XL'],
      colores: ['Negro'],
      otros_colores_img: [],
      caracteristicas: ['Tecnología Nike Dri-FIT', 'Bolsillo trasero'],
      composicion: '100% Poliéster',
      media: [
        {
          id: 1,
          producto_id: 1,
          url: 'https://images.unsplash.com/photo-1552346154-21d32810aba3?q=80',
          tipo: 'imagen',
          descripcion: '',
          es_principal: true,
        },
      ],
      reviews: [],
    },
    {
      id: 2,
      nombre: 'Zapatillas Running Zoom Pegasus 40 - Azul/Naranja',
      referencia: 102,
      descripcion:
        'Las Pegasus vuelven con una pisada elástica para alcanzar cualquier objetivo. Esta versión mantiene la misma reactividad que te encanta, pero con más comodidad en las zonas sensibles del pie.',
      marca: 'Nike',
      precio: 129.99,
      precio_oferta: 109.99, // ¡Oferta!
      visible: true,
      stock: 8,
      genero: 'Hombre',
      tallas: ['40', '41', '42', '43', '44', '45'],
      colores: ['Azul', 'Naranja'],
      otros_colores_img: [],
      caracteristicas: [
        'Soporte neutro para mayor equilibrio.',
        'Amortiguación media con tecnología Nike React.',
        'Malla de una sola capa muy transpirable.',
        'Suela tipo gofre para tracción en asfalto.',
      ],
      composicion: 'Material exterior: Malla técnica / Suela: Goma',
      media: [
        {
          id: 10,
          producto_id: 2,
          url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=2070&auto=format&fit=crop',
          tipo: 'imagen',
          descripcion: 'Vista lateral',
          es_principal: true,
        },
        {
          id: 11,
          producto_id: 2,
          url: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?q=80&w=1964&auto=format&fit=crop',
          tipo: 'imagen',
          descripcion: 'Detalle suela',
          es_principal: false,
        },
        {
          id: 12,
          producto_id: 2,
          url: 'https://images.unsplash.com/photo-1605348532760-6753d5c436da?q=80&w=2070&auto=format&fit=crop',
          tipo: 'imagen',
          descripcion: 'En uso',
          es_principal: false,
        },
      ],
      reviews: [
        {
          id: 3,
          usuario: 'Carlos M.',
          titulo: 'Comodidad total',
          comentario: 'Las uso para tiradas largas y son una maravilla.',
          valoracion: 5,
          fecha: '15/01/2026',
        },
      ],
    },
    {
      id: 3,
      nombre: 'Maillot Ciclismo Competizione - Rojo',
      referencia: 103,
      descripcion:
        'Maillot diseñado para entrenamientos intensos. Ofrece una aerodinámica excelente sin sacrificar la comodidad. Tejido Strada micro mesh ventilado en la parte delantera y trasera.',
      marca: 'Castelli',
      precio: 89.95,
      precio_oferta: null,
      visible: true,
      stock: 20,
      genero: 'Hombre',
      tallas: ['XS', 'S', 'M', 'L', 'XL'],
      colores: ['Rojo', 'Negro'],
      otros_colores_img: [],
      caracteristicas: [
        'Tejido elástico Tailwind con hoyuelos en hombros.',
        'Cremallera YKK® Vislon® de longitud integral.',
        'Elástico de silicona en la cintura.',
        '3 bolsillos traseros.',
      ],
      composicion: '90% Poliéster, 10% Elastano',
      media: [
        {
          id: 20,
          producto_id: 3,
          url: 'https://images.unsplash.com/photo-1616959952528-98e6bbe22df7?q=80&w=1974&auto=format&fit=crop',
          tipo: 'imagen',
          descripcion: 'Frontal',
          es_principal: true,
        },
        {
          id: 21,
          producto_id: 3,
          url: 'https://images.unsplash.com/photo-1524021226048-319985226177?q=80&w=2070&auto=format&fit=crop',
          tipo: 'imagen',
          descripcion: 'En ruta',
          es_principal: false,
        },
        {
          id: 22,
          producto_id: 3,
          url: 'https://images.unsplash.com/photo-1576435728678-35d0160d0141?q=80&w=2068&auto=format&fit=crop',
          tipo: 'imagen',
          descripcion: 'Detalle tejido',
          es_principal: false,
        },
      ],
      reviews: [],
    },
    {
      id: 4,
      nombre: 'Balón de Fútbol Pro League 24',
      referencia: 104,
      descripcion:
        'Balón oficial para partidos de alto nivel. Superficie termosellada sin costuras para una trayectoria más predecible, mejor toque y una menor absorción de agua.',
      marca: 'Adidas',
      precio: 140.0,
      precio_oferta: null,
      visible: true,
      stock: 50,
      genero: 'Unisex',
      tallas: ['Talla 5', 'Talla 4'],
      colores: ['Blanco', 'Multicolor'],
      otros_colores_img: [],
      caracteristicas: [
        'Certificación FIFA Quality Pro.',
        'Cámara de butilo para una mejor retención del aire.',
        'Superficie texturizada para mayor agarre.',
      ],
      composicion: '100% Poliuretano',
      media: [
        {
          id: 30,
          producto_id: 4,
          url: 'https://images.unsplash.com/photo-1614632537423-1e6c2e7e0aab?q=80&w=2074&auto=format&fit=crop',
          tipo: 'imagen',
          descripcion: 'Balón completo',
          es_principal: true,
        },
        {
          id: 31,
          producto_id: 4,
          url: 'https://images.unsplash.com/photo-1517466787929-bc90951d0974?q=80&w=1886&auto=format&fit=crop',
          tipo: 'imagen',
          descripcion: 'En el campo',
          es_principal: false,
        },
        {
          id: 32,
          producto_id: 4,
          url: 'https://images.unsplash.com/photo-1552667466-07770ae110d0?q=80&w=2070&auto=format&fit=crop',
          tipo: 'imagen',
          descripcion: 'Detalle textura',
          es_principal: false,
        },
      ],
      reviews: [
        {
          id: 4,
          usuario: 'Luisa G.',
          titulo: 'Calidad profesional',
          comentario: 'El toque es increíble, nada que ver con balones réplica.',
          valoracion: 5,
          fecha: '20/12/2025',
        },
      ],
    },
    {
      id: 5,
      nombre: 'Raqueta de Tenis Pure Strike 100',
      referencia: 105,
      descripcion:
        'Para jugadores ofensivos que buscan precisión. La Pure Strike 100 ofrece un control excepcional gracias a su patrón de encordado y la tecnología Control Frame.',
      marca: 'Babolat',
      precio: 219.0,
      precio_oferta: 199.95,
      visible: true,
      stock: 5,
      genero: 'Unisex',
      tallas: ['L2', 'L3', 'L4'],
      colores: ['Blanco', 'Naranja'],
      otros_colores_img: [],
      caracteristicas: [
        'Peso: 300g.',
        'Tamiz: 645 cm².',
        'Patrón de encordado: 16/19.',
        'Tecnología C² Pure Feel para mejor amortiguación.',
      ],
      composicion: 'Grafito',
      media: [
        {
          id: 40,
          producto_id: 5,
          url: 'https://images.unsplash.com/photo-1617083934555-56345cb2237e?q=80&w=1887&auto=format&fit=crop',
          tipo: 'imagen',
          descripcion: 'Raqueta entera',
          es_principal: true,
        },
        {
          id: 41,
          producto_id: 5,
          url: 'https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?q=80&w=2070&auto=format&fit=crop',
          tipo: 'imagen',
          descripcion: 'Mango',
          es_principal: false,
        },
        {
          id: 42,
          producto_id: 5,
          url: 'https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?q=80&w=2070&auto=format&fit=crop',
          tipo: 'imagen',
          descripcion: 'En pista',
          es_principal: false,
        },
      ],
      reviews: [],
    },
    {
      id: 6,
      nombre: 'Bañador Competición Mujer Fastskin',
      referencia: 106,
      descripcion:
        'Diseñado para competir. Ofrece compresión muscular inteligente y reduce la resistencia al agua. Aprobado por la FINA.',
      marca: 'Speedo',
      precio: 350.0,
      precio_oferta: null,
      visible: true,
      stock: 3,
      genero: 'Mujer',
      tallas: ['22', '24', '26', '28'],
      colores: ['Negro', 'Rosa'],
      otros_colores_img: [],
      caracteristicas: [
        'Costuras termoselladas.',
        'Tirantes confortables de perfil bajo.',
        'Tejido hidrófugo duradero.',
        'Compresión dual.',
      ],
      composicion: '65% Poliamida, 35% Elastano',
      media: [
        {
          id: 50,
          producto_id: 6,
          url: 'https://images.unsplash.com/photo-1576400883215-0593b96c3066?q=80&w=2070&auto=format&fit=crop',
          tipo: 'imagen',
          descripcion: 'Nadadora',
          es_principal: true,
        },
        {
          id: 51,
          producto_id: 6,
          url: 'https://images.unsplash.com/photo-1530549387789-4c1017266635?q=80&w=2070&auto=format&fit=crop',
          tipo: 'imagen',
          descripcion: 'Bajo el agua',
          es_principal: false,
        },
        {
          id: 52,
          producto_id: 6,
          url: 'https://images.unsplash.com/photo-1438029071396-1e831a7fa6d8?q=80&w=2000&auto=format&fit=crop',
          tipo: 'imagen',
          descripcion: 'Piscina',
          es_principal: false,
        },
      ],
      reviews: [
        {
          id: 5,
          usuario: 'Mireia B.',
          titulo: 'Rápido pero ajustado',
          comentario: 'Cuesta mucho ponérselo, pero una vez dentro se nota la hidrodinámica.',
          valoracion: 4,
          fecha: '02/01/2026',
        },
      ],
    },
    {
      id: 7,
      nombre: 'Camiseta Baloncesto Lakers Swingman',
      referencia: 107,
      descripcion:
        'Inspirada en la camiseta auténtica de la NBA. Tejido de malla de doble punto y detalles clásicos que rinden homenaje a la historia del equipo.',
      marca: 'Nike',
      precio: 95.0,
      precio_oferta: null,
      visible: true,
      stock: 12,
      genero: 'Hombre',
      tallas: ['S', 'M', 'L', 'XL', 'XXL'],
      colores: ['Amarillo', 'Morado'],
      otros_colores_img: [],
      caracteristicas: [
        'Tecnología Nike Dri-FIT.',
        'Gráficos aplicados con calor.',
        'Dobladillo recto para un ajuste cómodo.',
      ],
      composicion: '100% Poliéster reciclado',
      media: [
        {
          id: 60,
          producto_id: 7,
          url: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?q=80&w=2070&auto=format&fit=crop',
          tipo: 'imagen',
          descripcion: 'Jugando',
          es_principal: true,
        },
        {
          id: 61,
          producto_id: 7,
          url: 'https://images.unsplash.com/photo-1518063319789-7217e6706b04?q=80&w=1974&auto=format&fit=crop',
          tipo: 'imagen',
          descripcion: 'Detalle',
          es_principal: false,
        },
        {
          id: 62,
          producto_id: 7,
          url: 'https://images.unsplash.com/photo-1515523110800-9415d13b84a8?q=80&w=1974&auto=format&fit=crop',
          tipo: 'imagen',
          descripcion: 'Cancha',
          es_principal: false,
        },
      ],
      reviews: [],
    },
    {
      id: 8,
      nombre: 'Reloj Deportivo GPS Forerunner 965',
      referencia: 108,
      descripcion:
        'Reloj inteligente para triatletas y corredores. Pantalla AMOLED brillante, métricas de entrenamiento avanzadas y mapas a todo color.',
      marca: 'Garmin',
      precio: 649.99,
      precio_oferta: null,
      visible: true,
      stock: 4,
      genero: 'Unisex',
      tallas: ['Única'],
      colores: ['Negro', 'Blanco'],
      otros_colores_img: [],
      caracteristicas: [
        'Hasta 23 días de batería.',
        'Pantalla táctil AMOLED.',
        'Dinámicas de carrera en la muñeca.',
        'Estado de VFC.',
      ],
      composicion: 'Bisel de titanio / Lente Corning Gorilla Glass',
      media: [
        {
          id: 70,
          producto_id: 8,
          url: 'https://images.unsplash.com/photo-1551817958-c18561b4b985?q=80&w=1974&auto=format&fit=crop',
          tipo: 'imagen',
          descripcion: 'Reloj',
          es_principal: true,
        },
        {
          id: 71,
          producto_id: 8,
          url: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?q=80&w=1927&auto=format&fit=crop',
          tipo: 'imagen',
          descripcion: 'Corriendo',
          es_principal: false,
        },
        {
          id: 72,
          producto_id: 8,
          url: 'https://images.unsplash.com/photo-1557166983-5939644443a0?q=80&w=2070&auto=format&fit=crop',
          tipo: 'imagen',
          descripcion: 'Entrenamiento',
          es_principal: false,
        },
      ],
      reviews: [
        {
          id: 6,
          usuario: 'Jorge T.',
          titulo: 'El mejor reloj',
          comentario: 'La pantalla se ve increíble al sol y los mapas son súper útiles.',
          valoracion: 5,
          fecha: '11/02/2026',
        },
        {
          id: 7,
          usuario: 'Ana R.',
          titulo: 'Caro pero bueno',
          comentario: 'Es una inversión alta, pero si entrenas mucho vale la pena.',
          valoracion: 4,
          fecha: '14/02/2026',
        },
      ],
    },
  ])

  // 2. Definimos la función DESPUÉS
  const getProductById = (id: number) => {
    // IMPORTANTE: Al estar dentro del setup store, usamos .value
    return allProducts.value.find((p) => p.id === id)
  }

  // 3. Retornamos todo
  return { allProducts, getProductById }
})
